
package com.sforce.soap._2005._09.outbound;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotificationPort", targetNamespace = "http://soap.sforce.com/2005/09/outbound")
@XmlSeeAlso({
    com.sforce.soap._2005._09.outbound.ObjectFactory.class,
    com.sforce.soap.enterprise.sobject.ObjectFactory.class
})
public interface NotificationPort {


    /**
     * Process a number of notifications.
     * 
     * @param organizationId
     * @param notification
     * @param partnerUrl
     * @param actionId
     * @param sessionId
     * @param enterpriseUrl
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "Ack", targetNamespace = "http://soap.sforce.com/2005/09/outbound")
    @RequestWrapper(localName = "notifications", targetNamespace = "http://soap.sforce.com/2005/09/outbound", className = "com.sforce.soap._2005._09.outbound.Notifications")
    @ResponseWrapper(localName = "notificationsResponse", targetNamespace = "http://soap.sforce.com/2005/09/outbound", className = "com.sforce.soap._2005._09.outbound.NotificationsResponse")
    public boolean notifications(
        @WebParam(name = "OrganizationId", targetNamespace = "http://soap.sforce.com/2005/09/outbound")
        String organizationId,
        @WebParam(name = "ActionId", targetNamespace = "http://soap.sforce.com/2005/09/outbound")
        String actionId,
        @WebParam(name = "SessionId", targetNamespace = "http://soap.sforce.com/2005/09/outbound")
        String sessionId,
        @WebParam(name = "EnterpriseUrl", targetNamespace = "http://soap.sforce.com/2005/09/outbound")
        String enterpriseUrl,
        @WebParam(name = "PartnerUrl", targetNamespace = "http://soap.sforce.com/2005/09/outbound")
        String partnerUrl,
        @WebParam(name = "Notification", targetNamespace = "http://soap.sforce.com/2005/09/outbound")
        List<OFSClientMetadataLogInformationCNotification> notification);

}
